/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kuschel3DS (https://sketchfab.com/Kuschel3DS)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/classic-mazda-miata-cabriolet-low-poly-8bda7836f6514196b7b2fcf32c26d519
title: Classic Mazda Miata Cabriolet | Low Poly
*/

import React, { useRef, useState } from "react";
import { useGLTF, Html } from "@react-three/drei";

export default function Model(props) {
  const [active, setActive] = useState(false);
  const [r, setR] = useState(0.25);
  const [m, setM] = useState(0.5);
  const group = useRef();
  const { nodes, materials } = useGLTF("/model/scene.gltf");
  materials.Material.metalness = m;
  materials.Material.roughness = r;
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      onClick={(e) => {
        e.stopPropagation();
        setActive(!active);
      }}
    >
      {active && (
        <Html>
          <div
            style={{
              position: "absolute",
              top: "20px",
              left: "-50px",
              width: "100px",
              color: "white",
              fontFamily: "Arial, Sans Serif",
              fontSize: "12px"
            }}
          >
            <label>
              Roughness
              <input
                type={"range"}
                min={0}
                max={100}
                value={r * 100}
                onChange={(e) => setR(e.target.value / 100)}
              />
            </label>
            <label>
              Metalness
              <input
                type={"range"}
                min={0}
                max={100}
                value={m * 100}
                onChange={(e) => setM(e.target.value / 100)}
              />
            </label>
          </div>
        </Html>
      )}
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* Wing mirrors */}
        <mesh
          material={materials["Material.005"]}
          geometry={nodes.mesh_0.geometry}
          castShadow
          receiveShadow
        />
        <lineSegments
          material={materials["Material.009"]}
          geometry={nodes.mesh_1.geometry}
          castShadow
          receiveShadow
        />
        {/* Side lights */}
        <mesh
          material={materials["Material.009"]}
          geometry={nodes.mesh_2.geometry}
          castShadow
          receiveShadow
        />
        {/* Tail lights */}
        <mesh
          material={materials["Material.010"]}
          geometry={nodes.mesh_3.geometry}
          castShadow
          receiveShadow
        />
        {/* Body */}
        <mesh
          material={materials.Material}
          geometry={nodes.mesh_4.geometry}
          castShadow
          receiveShadow
        />
        {/* Interior */}
        <mesh
          material={materials["Material.001"]}
          geometry={nodes.mesh_5.geometry}
          castShadow
          receiveShadow
        />
        {/* Alloys */}
        <mesh
          material={materials["Material.002"]}
          geometry={nodes.mesh_6.geometry}
          castShadow
          receiveShadow
        />
        {/* Tyres */}
        <mesh
          material={materials["Material.003"]}
          geometry={nodes.mesh_7.geometry}
          castShadow
          receiveShadow
        />
        {/* Headlights */}
        <mesh
          material={materials["Material.004"]}
          geometry={nodes.mesh_8.geometry}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/scene.gltf");
