/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Kuschel3DS (https://sketchfab.com/Kuschel3DS)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/classic-mazda-miata-cabriolet-low-poly-8bda7836f6514196b7b2fcf32c26d519
title: Classic Mazda Miata Cabriolet | Low Poly
*/

import React, { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ position, scale, color, metal, rough }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/model/scene.gltf");

  useEffect(() => {
    materials.Material.color = {
      r: color.r / 100,
      g: color.g / 100,
      b: color.b / 100
    };
    materials.Material.metalness = metal;
    materials.Material.roughness = rough;
  }, [materials.Material, color, metal, rough]);
  return (
    <group ref={group} position={position} scale={scale} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        {/* Wing mirrors */}
        <mesh
          material={materials["Material.005"]}
          geometry={nodes.mesh_0.geometry}
          castShadow
          receiveShadow
        />
        <lineSegments
          material={materials["Material.009"]}
          geometry={nodes.mesh_1.geometry}
          castShadow
          receiveShadow
        />
        {/* Side lights */}
        <mesh
          material={materials["Material.009"]}
          geometry={nodes.mesh_2.geometry}
          castShadow
          receiveShadow
        />
        {/* Tail lights */}
        <mesh
          material={materials["Material.010"]}
          geometry={nodes.mesh_3.geometry}
          castShadow
          receiveShadow
        />
        {/* Body */}
        <mesh
          material={materials.Material}
          geometry={nodes.mesh_4.geometry}
          castShadow
          receiveShadow
        />
        {/* Interior */}
        <mesh
          material={materials["Material.001"]}
          geometry={nodes.mesh_5.geometry}
          castShadow
          receiveShadow
        />
        {/* Alloys */}
        <mesh
          material={materials["Material.002"]}
          geometry={nodes.mesh_6.geometry}
          castShadow
          receiveShadow
        />
        {/* Tyres */}
        <mesh
          material={materials["Material.003"]}
          geometry={nodes.mesh_7.geometry}
          castShadow
          receiveShadow
        />
        {/* Headlights */}
        <mesh
          material={materials["Material.004"]}
          geometry={nodes.mesh_8.geometry}
          castShadow
          receiveShadow
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model/scene.gltf");
